# Generated by Django 3.1.1 on 2020-09-20 06:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='Destinations')),
                ('description', models.TextField(max_length=1000)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('distincit_with', models.CharField(max_length=100)),
                ('price_for_adult', models.IntegerField()),
                ('website', models.URLField(null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
