# Generated by Django 3.1.1 on 2020-10-20 18:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='Destinations')),
                ('description', models.TextField(max_length=1000)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('distinct_with', models.CharField(blank=True, choices=[('near_beach', 'Near Beach'), ('near_mountain', 'Near Mountain')], max_length=100)),
                ('price', models.IntegerField()),
                ('website', models.URLField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(db_index=True, max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Destination_gallary')),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destination_app.destination')),
            ],
        ),
    ]
