# Generated by Django 3.1.1 on 2020-09-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='price_for_adult',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='country',
            new_name='traveling_to',
        ),
    ]
