# Generated by Django 3.1.1 on 2020-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0004_auto_20200920_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='traveling_to',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='destination',
            name='distincit_with',
            field=models.CharField(choices=[('near_beach', 'Near Beach'), ('near_mountain', 'Near Mountain')], max_length=100),
        ),
    ]
