# Generated by Django 3.1.1 on 2020-09-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0005_auto_20200920_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='distincit_with',
            new_name='distinct_with',
        ),
    ]
