# Generated by Django 3.1.1 on 2020-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0006_auto_20200920_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='distinct_with',
            field=models.CharField(blank=True, choices=[('near_beach', 'Near Beach'), ('near_mountain', 'Near Mountain')], max_length=100),
        ),
    ]
