# Generated by Django 3.1.1 on 2020-09-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0008_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countries',
        ),
    ]
