# Generated by Django 3.1.1 on 2020-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0009_delete_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
