# Generated by Django 3.1.1 on 2020-09-26 14:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0010_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='gallary',
            field=models.FileField(default='', upload_to='Destinations_gallary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
    ]
