# Generated by Django 3.1.1 on 2020-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0011_auto_20200926_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='gallary',
            field=models.FilePathField(allow_folders=True, path='Destination_gallary'),
        ),
    ]
