# Generated by Django 3.1.1 on 2020-09-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0012_auto_20200926_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='gallary',
        ),
        migrations.CreateModel(
            name='Destinationgallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='Destination_gallary')),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destination_app.destination')),
            ],
        ),
    ]
