# Generated by Django 3.1.1 on 2020-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0013_auto_20200926_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationgallary',
            name='images',
            field=models.ImageField(upload_to='Destination_gallary'),
        ),
    ]
