# Generated by Django 3.1.1 on 2020-10-06 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog_app', '0007_auto_20201006_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
