# Generated by Django 3.1.1 on 2020-10-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_postviewsunkown_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostViewsUnkown',
        ),
    ]
