# Generated by Django 3.1.1 on 2020-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_delete_postviewsunkown'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='IPAddres',
            field=models.GenericIPAddressField(default='45.243.82.162'),
        ),
    ]
