# Generated by Django 3.1.1 on 2020-10-14 10:30

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_auto_20201013_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.comment'),
        ),
    ]
