# Generated by Django 3.1.1 on 2020-10-14 14:46

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20201014_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
