# Generated by Django 3.1.1 on 2020-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201015_1417'),
        ('blog_app', '0021_remove_comment_reply_to_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='accounts.Profile'),
        ),
    ]
